### ISSUE TITLE
Also publish to JSR?

### ISSUE THREAD

**Issue by imcotton** [honojs/middleware#740]
From the **Hono** document:

> If you want to use Third-party Middleware with the TypeScript Type inferences, you need to use the npm: specifier. [^deno]

For package like `npm:@hono/valibot-validator`, this holding my back from using **Hono** from **JSR** by:

- `jsr:@hono/hono`
- `jsr:@valibot/valibot`

Any plans to have middleware packages also available on JSR too?

[^deno]: https://hono.dev/docs/getting-started/deno#npm-specifier

**Comment by yusukebe** [comment]
Hi @imcotton 

Supporting JSR is great. But there are some reasons I can't do it now:

* Making them support JSR will be hard. Especially removing slow types.
* Have to create deploy flow. I'm unsure if we can create a good flow to publicize them with `Changesets.`
* Maintenance costs will be increased. We(almost I) must also check the JSR things by adding npm packages.

**Comment by imcotton** [comment]
I think slow types is OK-ish for just publish with `--allow-slow-types` if it cost too much of effort.

Flow-wise, I think it'd be done by:
- having one corresponding `jsr.json` file
- add `deno publish` or `npx jsr publish` right after the `npm publish` on its CI

Maintenance indeed increased, but if I'm not missing anything else, above only be one time setup per package and then automatically carried afterwards.

Not sure the `jsr:@hono/*` is the intended place to publish these middleware, but right now it rather empty since only hosting the `jsr:@hono/hono` and nothing else.

I understand this is low priority and still up to decisions, in the meantime I could vendor the TypeScript source code by coping into my own project, but thought it worth to brought up to discussion, thanks for the participation.

**Comment by ingokpp** [comment]
+1 For JSR support. I really like the idea of not using npm at all in my deno project.

**Comment by dmint789** [comment]
+1 too. Would be nice to have the `@hono/zod-validator` package on there.

**Comment by azohra** [comment]
Took me longer than I care to admit to figure out these were not on JSR and that I had to use NPM. I am a newer Deno user and I can absolutely appreciate it may not be worth the effort to cross-publish. 

My small ask would be if updating the docs to indicate that the 3rd party portions are only available on NPM. Happy to make a PR if this would be a desired outcome.

**Comment by riderx** [comment]
My type is broken because it uses 2 different types apparently, and I think it's linked to this:
![CleanShot 2024-12-03 at 15 07 32](https://github.com/user-attachments/assets/b149c0b0-5284-4d1b-8935-61cc2e705b41)
It's important to have all in JSR if you need support for this my company can found it

**Comment by sant123** [comment]
It would be nice to have this repo published on JSR 🙏🏼

**Comment by NuroDev** [comment]
> +1 too. Would be nice to have the `@hono/zod-validator` package on there.

Big +1 to this. Currently if you try to use `jsr:@hono/hono` with `npm:@hono/zod-validator` it doesn't work because the env types clash.

I would guess if / when the day comes that Zod gets published to JSR (colinhacks/zod#3506) there may be more of an incentive to also publish `@hono/zod-validator` as well.

**Comment by yusukebe** [comment]
I've set up the flow to publish the package to JSR on `honojs/hono` repo. But currently, I'm not sure how we can do that in this "monorepo".

Hey @BarryThePenguin! Do you have time to work on this? We have to consider it if it's difficult to set up or maintain.

**Comment by BarryThePenguin** [comment]
Sure thing, I haven't spent much time with deno or JSR but I'm happy to take a look 👀

https://jsr.io/docs/publishing-packages

**Comment by NuroDev** [comment]
If it is of any help, I created the following GitHub action in another project to deploy to JSR in a "monorepo" style structure. Entirely opt-in for each package you want to publish.

```yaml
name: Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    strategy:
      fail-fast: false
      matrix:
        package: []
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Publish to JSR
        run: npx jsr publish
        working-directory: ./packages/${{ matrix.package }}
```
